stages:
  - build

backend-build-artifacts:
  stage: build
  image: golang
  cache:
    key: golang-backend
    paths:
      - ${GOLANG_CACHE_PATH}
  script:
    - cd backend
    - go test -v ./..
    - go build ./cmd/api
    - mv ./api ./backend-pelmeni-store-${APP_VERSION}
  artifacts:
    untracked: false
    expire_in: "7 days"
    paths:
      - ${CI_PROJECT_DIR}/backend/backend-pelmeni-store-${APP_VERSION}
