stages:
  - build

backend-build-artifacts:
  stage: build
  image: golang
  cache:
    key: golang-backend
    paths:
      - ${GOCACHE}
  script:
    - cd backend
    - go test -v ./...
    - go build ./cmd/api
    - mv ./api ./${APP_NAME}-backend-${APP_VERSION}
  artifacts:
    untracked: false
    expire_in: "7 days"
    paths:
      - ${CI_PROJECT_DIR}/backend/${APP_NAME}-backend-${APP_VERSION}

backend-build-docker-image:
  stage: build
  cache:
    key: golang-backend
    paths:
      - ${GOCACHE}
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --build-arg GOCACHE=${GOCACHE}
      --use-new-run
      --cache=true
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${APP_NAME}-backend:${CI_PIPELINE_ID}"
