---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerpull
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
data:
  .dockerconfigjson: null
---
apiVersion: v1
data:
  tls.crt: null
  tls.key: null
kind: Secret
metadata:
  creationTimestamp: "2022-11-05T18:06:45Z"
  name: ian-bodrievskii.ru-tls
  namespace: default
  resourceVersion: "254485"
  uid: 1c060e03-a2a5-45ad-b21b-5499b76b6917
type: kubernetes.io/tls
