apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelmeshki-backend
spec:
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: pelmeshki-backend
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: pelmeshki-backend
    spec:
      imagePullSecrets:
        - name: dockerpull
      containers:
      - name: pelmeshki-backend
        imagePullPolicy: "Always"
        image: gitlab.praktikum-services.ru:5050/yan-bodriyevskiy/pelmeni-store/pelmeshki-backend:latest
        ports:
          - containerPort: 8081
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
