---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pelmeski-ingress
  labels:
    name: pelmeski-ingress
spec:
  ingressClassName: "nginx"
  rules:
    - host: pelmeshki-store.tech
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: pelmeski-frontend-service
              port:
                number: 80
