---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerpull
  labels:
    app.kubernetes.io/name: '{{ .Release.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Chart.Name }}-secret'
    app.kubernetes.io/version: '{{ .Values.tag }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    app.kubernetes.io/component: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: '{{ .Release.Name }}'
    env: '{{ .Values.global.environment }}'
data:
  .dockerconfigjson: null
---
apiVersion: v1
data:
  tls.crt: null
  tls.key: null
kind: Secret
metadata:
  name: ian-bodrievskii.ru-tls
  labels:
    app.kubernetes.io/name: '{{ .Release.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}-{{ .Chart.Name }}-secret'
    app.kubernetes.io/version: '{{ .Values.tag }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    app.kubernetes.io/component: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: '{{ .Release.Name }}'
    env: '{{ .Values.global.environment }}'
type: kubernetes.io/tls
